# Generated by Django 5.0.6 on 2024-07-01 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopuser',
            name='birth_date',
        ),
    ]
