# Generated by Django 5.0.6 on 2024-07-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_user', '0002_remove_shopuser_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
